=== matthiaw/react-rxdb-jsonform-example/src/schemas/person.schema.json
{
	"definitions": {
		"name": {
			"title": "Name of Person",
			"type": "object",
			"properties": {
				"firstname": {
					"type": "string",
					"title": "First Name"
				},
				"secondname": {
					"type": "string",
					"title": "Second name"
				},
				"familyname": {
					"type": "string",
					"title": "Family Name"
				}
			},
			"required": [
				"firstname",
				"familyname"
			]
		},
		"phone": {
			"type": "object",
			"properties": {
				"number": {
					"type": "string",
					"title": "Number",
					"description": "Phone-Number"
				},
				"type": {
					"type": "string",
					"title": "Type",
					"description": "Type of number.",
					"enum": [
						"private",
						"bussiness",
						"mobile",
						"fax"
					]
				}
			},
			"required": [
				"number",
				"type"
			]
		},
		"address": {
			"type": "object",
			"properties": {
				"street": {
					"type": "string",
					"title": "Streetname",
					"description": "Name of the street with the number."
				},
				"zip": {
					"type": "string",
					"title": "The zip-code of the city"
				},
				"city": {
					"type": "string",
					"title": "The name of the city"
				},
				"country": {
					"type": "string",
					"enum": [
						"germany",
						"france"
					],
					"title": "The country",
					"default": "germany"
				},
				"type": {
					"type": "string",
					"enum": [
						"residential",
						"bussiness"
					],
					"title": "Type of Adress",
					"default": "Could be residential or bussiness."
				}
			},
			"required": [
				"street",
				"zip",
				"city",
				"country",
				"type"
			]
		}
	},
	"$schema": "http://json-schema.org/draft-06/schema#",
	"$id": "http://example.com/example.json",
	"type": "object",
	"properties": {
		"id": {
			"$id": "/properties/id",
			"type": "integer",
			"title": "Id of Person",
			"examples": [
				1
			]
		},
		"name": {
			"$ref": "#/definitions/name"
		},
		"abbreviation": {
			"$id": "/properties/abbreviation",
			"type": "string",
			"title": "Abbreviation",
			"pattern": "[A-Z]+",
			"examples": [
				"MW"
			]
		},
		"phones": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/phone"
			}
		},
		"adresses": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/address"
			}
		},
		"status": {
			"$id": "/properties/status",
			"type": "string",
			"enum": [
				"active",
				"inactive"
			],
			"title": "Status",
			"examples": [
				"active"
			]
		}
	},
	"required": [
		"id",
		"name"
	]
}

=== matthiaw/react-rxdb-jsonform-example/src/schemas/matthias_wegner.person.json
{
	"id": 1230,
	"name": {
		"firstname": "Matthias",
		"familyname": "Wegner"
	},
	"abbreviation": "MW",
	"phones": [
		{
			"number": "+49 123 45678",
			"type": "mobile"
		},
		{
			"number": "07661 1111111",
			"type": "private"
		}
	],
	"adresses": [
		{
			"street": "LÃ¶wenstrasse 1",
			"zip": "79199",
			"city": "Kirchzarten",
			"country": "germany",
			"type": "residential"
		}
	],
	"status": "active"
}
